name: mongo-sharding-repl
services:
  #сервер конфигурации
  configSrv:
    image: mongo:latest # docker образ
    container_name: configSrv 
    restart: always
    ports:
      - "27019:27019"
    # networks:
    #   app-network:
    #     ipv4_address: 173.17.0.0
    volumes:
      - config-data:/data/db
    command:
      [
        "--configsvr",  #запуск в режиме конфигурации
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27019"
      ] 
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #1-я реплика 1-го шарда
  shard1_1:
    image: mongo:latest
    container_name: shard1_1
    restart: always
    ports:
      - "27030:27030"
    # networks:
    #   app-network:
    #     ipv4_address: 173.17.0.1
    volumes:
      - shard1_1-data:/data/db
    command:
      [
        "--shardsvr", #запуск в режиме шардинга
        "--replSet",
        "shard1", #название реплики
        "--bind_ip_all",
        "--port",
        "27030"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #2-я реплика 1-го шарда
  shard1_2:
    image: mongo:latest
    container_name: shard1_2
    restart: always
    ports:
      - "27031:27031"
    # networks:
    #   app-network:
    #     ipv4_address: 173.17.0.2
    volumes:
      - shard1_2-data:/data/db
    command:
      [
        "--shardsvr", #запуск в режиме шардинга
        "--replSet",
        "shard1", #название реплики
        "--bind_ip_all",
        "--port",
        "27031"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #3-я реплика 1-го шарда
  shard1_3:
    image: mongo:latest
    container_name: shard1_3
    restart: always
    ports:
      - "27032:27032"
    # networks:
    #   app-network:
    #     ipv4_address: 173.17.0.3
    volumes:
      - shard1_3-data:/data/db
    command:
      [
        "--shardsvr", #запуск в режиме шардинга
        "--replSet",
        "shard1", #название реплики
        "--bind_ip_all",
        "--port",
        "27032"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #1-я реплика 2-го шарда
  shard2_1:
    image: mongo:latest
    container_name: shard2_1
    restart: always
    ports:
      - "27040:27040"
    # networks:
    #   app-network:
    #     ipv4_address: 173.17.0.4
    volumes:
      - shard2_1-data:/data/db
    command:
      [
        "--shardsvr", #запуск в режиме шардинга
        "--replSet",
        "shard2", #название реплик
        "--bind_ip_all",
        "--port",
        "27040"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #2-я реплика 2-го шарда
  shard2_2:
    image: mongo:latest
    container_name: shard2_2
    restart: always
    ports:
      - "27041:27041"
    # networks:
    #   app-network:
    #     ipv4_address: 173.17.0.5
    volumes:
      - shard2_2-data:/data/db
    command:
      [
        "--shardsvr", #запуск в режиме шардинга
        "--replSet",
        "shard2", #название реплики
        "--bind_ip_all",
        "--port",
        "27041"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #3-я реплика 2-го шарда
  shard2_3:
    image: mongo:latest
    container_name: shard2_3
    restart: always
    ports:
      - "27042:27042"
    # networks:
    #   app-network:
    #     ipv4_address: 173.17.0.6
    volumes:
      - shard2_3-data:/data/db
    command: 
      [
        "--shardsvr", #запуск в режиме шардинга
        "--replSet",
        "shard2", #название реплики
        "--bind_ip_all",
        "--port",
        "27042"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
      
  
  #роутер
  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27017:27017"
    # networks:
    #   app-network:
    #     ipv4_address: 173.17.0.7
    command:
      [
        "mongos", #обычная mongo в режиме роутера
        "--configdb", 
        "config_server/configSrv:27019", #передача данных сервера конфигурации
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos_router
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27017"
      MONGODB_DATABASE_NAME: "somedb"


# networks:
#   app-network:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 173.17.0.0/16

volumes:
  config-data:
  shard1_1-data:
  shard1_2-data:
  shard1_3-data:
  shard2_1-data:
  shard2_2-data:
  shard2_3-data:
 